### ISSUE TITLE
add test to verify the YAML file

### ISSUE THREAD

**Issue by ejhumphrey** [ismir/mir-datasets#1]
tests should verify that
- [ ] the yaml can be read
- [ ] all URLs don't return a 400+?

maybe other things?

**Comment by faroit** [comment]
I will try to find some time for this. I would do it in py.test, ok?

**Comment by ejhumphrey** [comment]
❤️ pytest! We've already got the requirements file, so a `test_database.py` or equivalent will be 👌 

I'm realizing that there are actually *two* things to be done here – add the test file to verify the yaml  is valid, and then (later) actually setting this up in a CI/CD framework, e.g. Travis, circle-ci, etc. I'll update this issue to be only the former, and create a new issue for the CI/CD thing specifically, which is a heavier (and subsequent) lift.

**Comment by faroit** [comment]
Started in #8, it also integrates CI, hence #7.

>  all URLs don't return a 400+?

I check for 200, is this too strict?

**Comment by stefan-balke** [comment]
Integrated.
