### ISSUE TITLE
Timeout build errors?

### ISSUE THREAD

**Issue by alexanderlerch** [ismir/mir-datasets#32]
The last two pull requests throw an error although they seem to be correct. It looks like the build is stalled for some reason. See, for example, the build protocol mentioning the time-out [here](https://travis-ci.com/github/ismir/mir-datasets/builds/196032987)

**Comment by sebastianrosenzweig** [comment]
It seems that this problem is not solved yet. @stefan-balke Do you have an idea?

**Comment by sebastianrosenzweig** [comment]
Update: I am currently having a look and it seems that get_status_url() is not terminating in time...

**Comment by sebastianrosenzweig** [comment]
This issue should be solved by #35
