### ISSUE TITLE
Integrate repo with CI/CD platform

### ISSUE THREAD

**Issue by ejhumphrey** [ismir/mir-datasets#7]
There are two uses we have for automated continuous delivery / integration:
- make sure changes to the YAML file are valid and don't break any of the rendering scripts #1 
- render and update the build outputs #5 

This is a pretty lightweight repo, and TravisCI is probably fine. Curious if there are arguments for / against this or another platform.

**Comment by faroit** [comment]
When the tests start to succeed, lets enable cron jobs on travis to trigger the test daily so we get notified if a url is outdated.

**Comment by stefan-balke** [comment]
So far, so good, Markdown and JS files are there:
https://github.com/ismir/mir-datasets/blob/gh-pages/outputs/data-sets.md

However, website is not showing up:
https://ismir.github.io/mir-datasets/

Any ideas? Console says there's no js file...cannot confirm that :)

**Comment by stefan-balke** [comment]
okay, working now. Was a problem in the Repo-settings (pointing to `docs/`)
